# Generated by Django 4.0.4 on 2022-07-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0),
        ),
    ]
