# Generated by Django 4.0.4 on 2022-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_variacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
